// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL_td06rUMK0Q_vLmWQQoAQa-Won3S25s',
    appId: '1:1081756160975:web:8c125cb99ddb0b692078ba',
    messagingSenderId: '1081756160975',
    projectId: 'bhinder-internet',
    authDomain: 'bhinder-internet.firebaseapp.com',
    storageBucket: 'bhinder-internet.appspot.com',
    measurementId: 'G-QWDQPEHMWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPSlkoAuPxu50MTmiGmVGzxZNR8wEi54Y',
    appId: '1:1081756160975:android:750360d533af5f802078ba',
    messagingSenderId: '1081756160975',
    projectId: 'bhinder-internet',
    storageBucket: 'bhinder-internet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZTVXH1-DiMX09mbXQznFKwQbPukrrtw',
    appId: '1:1081756160975:ios:7b682844b7f9c89d2078ba',
    messagingSenderId: '1081756160975',
    projectId: 'bhinder-internet',
    storageBucket: 'bhinder-internet.appspot.com',
    iosBundleId: 'com.example.bhinderInternet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFZTVXH1-DiMX09mbXQznFKwQbPukrrtw',
    appId: '1:1081756160975:ios:7b682844b7f9c89d2078ba',
    messagingSenderId: '1081756160975',
    projectId: 'bhinder-internet',
    storageBucket: 'bhinder-internet.appspot.com',
    iosBundleId: 'com.example.bhinderInternet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL_td06rUMK0Q_vLmWQQoAQa-Won3S25s',
    appId: '1:1081756160975:web:f66a57bcbeb939362078ba',
    messagingSenderId: '1081756160975',
    projectId: 'bhinder-internet',
    authDomain: 'bhinder-internet.firebaseapp.com',
    storageBucket: 'bhinder-internet.appspot.com',
    measurementId: 'G-3HJJPLL6C4',
  );
}
